### ISSUE TITLE
This is an amazing theme ! please update it as much as possible

### ISSUE THREAD

**Issue by enzime4u** [Jean-Tinland/vscode-theme-night-shift#1]
I love the theme very much, can you please add a iTerm2 version of it ?

**Comment by Jean-Tinland** [comment]
Thanks! I'm really glad you like it!

I've created a repo containing my iTerm2 theme (light & dark). 
You'll find it [here](https://github.com/Jean-Tinland/iTerm2-theme-desaturated).

Let me know if it's need some adjustments.

**Comment by enzime4u** [comment]
thank you
