### ISSUE TITLE
File Highlight in Vscode tree

### ISSUE THREAD

**Issue by enzime4u** [Jean-Tinland/vscode-theme-night-shift#2]
It is very hard to see the file that you are on in VSCode file-tree ... can you add a bg color or something?

**Comment by Jean-Tinland** [comment]
Indeed, I'll work on something soon!

**Comment by enzime4u** [comment]
thank you ! 👍

**Comment by Jean-Tinland** [comment]
I improved the current file highlight visibility in file tree. You can update to 3.0.2 and let me know if this is better.

And thanks for the tips.

**Comment by enzime4u** [comment]
it looks better 👍 
Thank you . If I come with more ideas I will let you know !

**Comment by Jean-Tinland** [comment]
Thanks! I welcome any idea which would improve the quality of this theme.
