### ISSUE TITLE
Background color for current selected ! 

### ISSUE THREAD

**Issue by enzime4u** [Jean-Tinland/vscode-theme-night-shift#3]
Please update the highlight color while navigating thru oprtions ( I suggest a darker one or same as file-tree-color ) 
Thank you
![Screen Shot 2020-11-04 at 14 13 20](https://user-images.githubusercontent.com/10274752/98110583-f7299000-1ea7-11eb-8935-88d0ecdedd47.png)

**Comment by Jean-Tinland** [comment]
Hi, indeed, I missed that. This should fixed in 3.0.3.

**Comment by enzime4u** [comment]
great !
