### ISSUE TITLE
Theme sugestion

### ISSUE THREAD

**Issue by enzime4u** [Jean-Tinland/vscode-theme-night-shift#4]
Hey, I found this website : [https://slackthemes.net](url)
woudl be nice to create some slack themes according to the palette from Night Shift theme .

Have a good evening

**Comment by Jean-Tinland** [comment]
I created a set of colors base on Night Shift:

`#1E2737,#1B222D,#39465E,#FFF9EE,#1B222D,#FFF9EE,#8FC8BB,#E78482`

I think I'll create a gist of it.

**Comment by enzime4u** [comment]
Thank you. Just one question: why are you using a background color which is lighter than the VS Code original theme ?

**Comment by Jean-Tinland** [comment]
You are right, here a more consistent version of it:

`#1B222D,#1B222D,#1E2737,#98A8C5,#1B222D,#FFF9EE,#8FC8BB,#E78482,#1B222D,#FFF9EE`

**Comment by enzime4u** [comment]
great ! Thank you
