### ISSUE TITLE
Multiple terminal windows !!!! 

### ISSUE THREAD

**Issue by enzime4u** [Jean-Tinland/vscode-theme-night-shift#5]
Hi there, since I am using daily vscode with your theme , I noticed somehting : 
when opening multiple terminal windows it is very hard to see in which one you are and also the border/margins of it

Maybe you come up with and idea on how to solve this . 

please see image below.

Super-thank you
![Screen Shot 2020-11-12 at 16 36 52](https://user-images.githubusercontent.com/10274752/98953526-7270ee80-2505-11eb-8dfc-3897403abd36.png)

**Comment by Jean-Tinland** [comment]
I'll try something to improve this. Maybe set the border color to yellow? It would contrast enough with the background I think.

**Comment by enzime4u** [comment]
i think it will be better, also shadow will help , in order to have everything dark-mode :)

**Comment by Jean-Tinland** [comment]
Hi, I've published a new version of my theme (3.0.4) with a new color for the integrated terminal & editor split panes.

Tell me if this is OK, I tried several colors and this one seems to be contrasted enough.

**Comment by enzime4u** [comment]
it looks way better ! 

I have a new suggestion , should I add it here? or make a new Issues ?

**Comment by Jean-Tinland** [comment]
You can add it here :)

Thanks for all your suggestions!

**Comment by enzime4u** [comment]
I think that the files colors in the file-tree on the right shouldn't be white , they should be more grayish and just the active one should be white ! what do you think ?

**Comment by enzime4u** [comment]
I think this color: #99a7b8

**Comment by enzime4u** [comment]
![Screenshot 2020-11-19 at 01 11 58](https://user-images.githubusercontent.com/10274752/99599575-4de4ad00-2a04-11eb-83e2-eb8c73797a4c.png)
that is from Ocean Code vscode theme : `https://github.com/JesseKuntz/ocean-code`

**Comment by Jean-Tinland** [comment]
I updated the colors in the file tree to be less bright in 3.0.5. :)
I reuse a color from Night Shift theme in order to keep an harmony.

**Comment by enzime4u** [comment]
it looks amazing !!!!
