### ISSUE TITLE
Theme Home Page?

### ISSUE THREAD

**Issue by enzime4u** [Jean-Tinland/vscode-theme-night-shift#7]
I think also that it would be nice to have a github.io landing page for this theme ! It is a great theme !

**Comment by Jean-Tinland** [comment]
Indeed, I'd like to create one when I'll have more time working on this. Thanks for the suggestion!

**Comment by Jean-Tinland** [comment]
I created a minimal theme page [here](https://jean-tinland.github.io/night-shift-demo/).

I'll link it soon in the theme description. It will surely evolve soon depending on my availability.

**Comment by enzime4u** [comment]
🤩

**Comment by Jean-Tinland** [comment]
The theme home page has moved [here](https://www.jeantinland.com/en/toolbox/night-shift-theme/) :)
