### ISSUE TITLE
What is the file icon theme?

### ISSUE THREAD

**Issue by fuadnafiz98** [Jean-Tinland/vscode-theme-night-shift#8]
What is the file icon theme you used in the readme previews? 
Thanks in advance :100:

**Comment by Jean-Tinland** [comment]
I'm using [city lights](https://marketplace.visualstudio.com/items?itemName=Yummygum.city-lights-icon-vsc), the colored one. :)

**Comment by fuadnafiz98** [comment]
Thanks for answering the silly question
